### PR TITLE
Matthew's branch

### PR DESCRIPTION
**Pull request by mklsm**
fix various warnings as well as removed any code that is not needed.

### CODE REVIEW

**Comment by joshschriever** [comment]
The inner classes that make all the test data are temporary; do they really need all those serial version uid's?

**Comment by mklsm** [comment]
technically no, but it is a standard to have it in every class you make. I was wondering the same thing myself, besides I hate seeing 74 warning messages when opening this up in eclipse.

**Comment by joshschriever** [comment]
Ok. I'm going to wait to merge this until Jessica and I finish up a couple other things.

**Comment by mklsm** [comment]
makes sense.

**Comment by mklsm** [comment]
added implementation to InventoryPanel for the Add Button. Also Save doesn't seem to work right....

**Pull request merged**
